# DATA HANDLING  WITH PANDAS (SERIES)


In [8]:
# CREATING BLANK SERIES 
import numpy as np
import pandas as pd 
A=np.array([])
A1=pd.Series(A)
print(A1)

Series([], dtype: float64)


In [14]:
# CREATING SERIES USING DICTRIONARIES 
import pandas as pd
import numpy as np
A={1:'om',2:'aryan',3:'viraj',4:'kavyansh'}
A2=pd.Series(A)
print(A2)

1          om
2       aryan
3       viraj
4    kavyansh
dtype: object


In [10]:
# random numbers between 0 to 100 5 by 5 matrix 
import numpy as np
a=np.random.randint(0,100,(5,5))
print(a)

[[59 26 53 99 92]
 [49 14 98 78 28]
 [ 2 89 87 28 89]
 [40 36 35 67 98]
 [62 40 73 94  2]]


In [16]:
# creatring series with attributes hasnans
import pandas as pd 
a=pd.Series([12,3,4,None])
print(a)
print(a.hasnans)

0    12.0
1     3.0
2     4.0
3     NaN
dtype: float64
True


In [22]:
#creating a series with the attribute indexing
import pandas as pd
A=pd.Series(['a','b','c',4,5])
print(A,A.index)

0    a
1    b
2    c
3    4
4    5
dtype: object RangeIndex(start=0, stop=5, step=1)


In [4]:
# METHAMATICAL OPERATIONS (ADD)
import pandas as pd
s1=pd.Series([20,30,36,38,45],index=['A','B','C','D','E'])
s2=pd.Series([75,34,56,12,86],index=['A','F','D','G','E'])
data=s1.add(s2)
print (data)

A     95.0
B      NaN
C      NaN
D     94.0
E    131.0
F      NaN
G      NaN
dtype: float64


In [7]:
# MATHEMATICAL OPERATIONS (ADD)
import pandas as pd
s1=pd.Series([20,30,36,38,45],index=['A','B','C','D','E'])
s2=pd.Series([75,34,56,12,86],index=['A','F','D','G','E'])
data=s1.add(s2,fill_value=100)#data=s1+s2
print (data)


A     95.0
B    130.0
C    136.0
D     94.0
E    131.0
F    134.0
G    112.0
dtype: float64


In [9]:
#MATHEMATICAL OPERATIONS (SUBTRACT)
import pandas as pd
s1=pd.Series([20,30,36,38,45],index=['A','B','C','D','E'])
s2=pd.Series([75,34,56,12,86],index=['A','F','D','G','E'])
data=s1.sub(s2,fill_value=100)
print (data)

A   -55.0
B   -70.0
C   -64.0
D   -18.0
E   -41.0
F    66.0
G    88.0
dtype: float64


In [15]:
# MATHEMATICAL OPERATIONS (SUBTRACT)
import pandas as pd
s1=pd.Series([20,30,36,38,45],index=['A','B','C','D','E'])
s2=pd.Series([75,34,56,12,86],index=['A','F','D','G','E'])
data=s1.sub(s2)
print (data)

A   -55.0
B     NaN
C     NaN
D   -18.0
E   -41.0
F     NaN
G     NaN
dtype: float64


In [16]:
#MATHEMATICAL OPERATIONS (DIVISION)
import pandas as pd
s1=pd.Series([20,30,36,38,45],index=['A','B','C','D','E'])
s2=pd.Series([75,34,56,12,86],index=['A','F','D','G','E'])
data=s1.div(s2)
print (data)

A    0.266667
B         NaN
C         NaN
D    0.678571
E    0.523256
F         NaN
G         NaN
dtype: float64


In [17]:
#MATHEMATICAL OPERATIONS (DIVISION)
import pandas as pd
s1=pd.Series([20,30,36,38,45],index=['A','B','C','D','E'])
s2=pd.Series([75,34,56,12,86],index=['A','F','D','G','E'])
data=s1.div(s2,fill_value=100)
print (data)

A    0.266667
B    0.300000
C    0.360000
D    0.678571
E    0.523256
F    2.941176
G    8.333333
dtype: float64


In [18]:
#MATHEMATICAL OPERATIONS (MULTIPLICATION)
import pandas as pd
s1=pd.Series([20,30,36,38,45],index=['A','B','C','D','E'])
s2=pd.Series([75,34,56,12,86],index=['A','F','D','G','E'])
data=s1.mul(s2)
print (data)

A    1500.0
B       NaN
C       NaN
D    2128.0
E    3870.0
F       NaN
G       NaN
dtype: float64


In [19]:
#MATHEMATICAL OPERATIONS (MULTIPLICATION)
import pandas as pd
s1=pd.Series([20,30,36,38,45],index=['A','B','C','D','E'])
s2=pd.Series([75,34,56,12,86],index=['A','F','D','G','E'])
data=s1.mul(s2,fill_value=100)
print (data)

A    1500.0
B    3000.0
C    3600.0
D    2128.0
E    3870.0
F    3400.0
G    1200.0
dtype: float64


In [3]:
# USING HEAD FUNCTION 
import pandas as pd
s=pd.Series(data=[1,2,3,4,5],index=[6,7,8,9,10])
print(s)
print(s.head())

6     1
7     2
8     3
9     4
10    5
dtype: int64
6     1
7     2
8     3
9     4
10    5
dtype: int64


In [6]:
# USING TAIL FUNTION
import pandas as pd
s1=pd.Series(data=['a','b','c','d','e'],index=[1,2,3,4,5])
s1.index.name='tail function '
s1.name='tail'
print(s1,s1.head(3))

tail function 
1    a
2    b
3    c
4    d
5    e
Name: tail, dtype: object tail function 
1    a
2    b
3    c
Name: tail, dtype: object


In [1]:
# USING COUNT FUCTION
import pandas as pd
s=pd.Series(data=[1,2,3,4,5],index=['a','b','s','d','f'])
print(s)
print(s.count())
print(s.min())
print(s.max())

a    1
b    2
s    3
d    4
f    5
dtype: int64
5
1
5
